# 异常处理

## 语法异常

语法异常又被称为解析异常, 解析器会输出出现语法错误的哪一行, 并可显示一个"箭头", 执行这行里面检测到第一个错误。

```python
>>> while True print("Hello world")
  File "<stdin>", line 1
    while True print('Hello world')
                   ^
SyntaxError: invalid syntax
```



## 异常

即使语句或表达式在语法上是正确的, 但在尝试执行时, 仍然可能会引发错误。在执行时检测到的错误被称为_异常_.

```python
>>> 10 * (1/0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> 4 + spam*3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spam' is not defined
>>> '2' + 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't convert 'int' object to str implicitly
```



## 处理异常

可以编写处理所选异常的程序。

```python
>>> while True:
     try:
            x = int(input("Please enter a number: "))
         break
     except ValueError:
         print("Oops!  That was no valid number.  Try again...")

```

### try 语句的工作原理如下:

- 首先, 执行try子句(try 和except 关键字之间的多行语句)
- 如果没有发生异常, 则跳过_except_ 子句并完成`try`语句的执行
- 如果在执行_try_子句时发生异常, 则跳过该子句中剩下的部分。然后，如果异常的类型和_except_关键字后面的类型匹配, 则执行_except_子句, 然后继续执行_try_语句之后的代码
- 如果发生的异常和_except_子句中指定的异常不匹配, 则将其传递到外部的_try_语句中; 如果没有找到处理程序, 则它是一个_未处理异常_, 执行将停止并显示如上所示的消息.



一个`try`语句可能有多个_except_子句, 以指定不同类型的处理程序。最多会执行一个处理程序。处理程序只处理相应的_try_子句中发生的异常，而不处理同一_try_语句内其他处理程序中的异常。一个_except_子句可以将多个异常命名为带括号的元祖, 例如:

```python
except (RuntimeError, TypeError, NameError)
	pass
```



### else

`try...except`语句有一个可选的_else_子句, 在使用时必须放在所有的_except_子句后面. 对于_try_子句`不引发异常时必须执行的代码来说很有用`.

使用__else__子句比向__try__子句添加额外的代码要好, 因为它避免了额外捕获由__try...except__语句保护的代码未引发的异常。

发生异常时, 它可能具有关联值, 也称为异常__参数__. 参数的存在和类型取决于异常类型.

### except

except 子句可以在异常名称后面指定一个变量. 这个变量和一个异常实例绑定, 它的参数存储在`instance.args`中。为了方便起见, 异常实例定义了`__str__()`, 因此可以直接打印参数而无需引用`.args()`. 也可以在抛出之前首先实例化异常,  并根据需要向其添加任何属性。



## 抛出异常

`raise`语句允许程序员强制发生指定的异常:

```python
raise NameError('HiThere')
```

`raise`唯一的参数就是要跑出的异常. 这个参数必须是一个异常实例或者一个异常类(派生自`Exception`的类)。如果传递的是一个异常类， 他将通过调用没有参数的构造函数来隐式实例化:

```python
raise ValueError
```



如果你需要确认是否发生了异常但是不打算处理它, 则可以使用更简单的`raise`语句形式重新引发异常.

```python
try:
    raise NameError('HiThere')
except:
    print("An exception flew by!")
    raise
```

## 用户自定义异常

程序可以通过创建新的异常类来命名他们自己的异常。异常通常应该直接地或间接地从`Exception`类派生。

可以定义异常类, 他可以执行任何其他类可以执行的任何操作，但通常保持简单，通常只提供许多属性，这些属性允许处理程序为异常提取有关错误的信息。在创建可能引发多个不同错误的模块时, 通常的做法是为该模块定义的异常创建基类, 并未不同条件创建特定异常的子类。

```python
class Error(Exception):
    """Base class for exceptions in this module"""
    pass

class InputError(Error):
    """Exception raised for errors in the input.
    Attributes:
    	exceptions -- input expresion in which the error occurred.
    	message -- explanation of the error
    """
    def __init__(sef, expression, message):
        self.expression = expression
        self.message = message
        
class TransitionError(Error):
    """Raised when an operation attempts a state transition that's not allowed.
    Attributes:
    	previous -- state at begining of transition
    	next -- attempted new state
    	message -- explanation of why the specific transition is not allowed
    """
    def __init__(self, previous, next, message):
        self.previous = previous
        self.next = next
        self.message = message
```

大多数异常都定义为"Error"结尾, 类似于标准异常的命令。



## 定义清理操作

`try`语句有一个可选子句, 用于定义必须在所有清凉下执行的清理操作.

```python
try:
    raise KeboardInterrupt
finally:
    print("hello world")
```

如果存在`finally`子句, 则`finally`子句将作为`try`语句结束前的最后一项任务呗执行。`finally`子句不论`try`语句是否产生了异常都会被执行。以下讨论了当异常发生时一些更复杂的情况:

- 如果在执行`try`子句期间发生了异常, 该异常可有`except`子句进行处理。如果异常没有被`except`子句所处理, 则该异常会在`finally`子句之后被重新引发。
- 如果在执行`try`语句时遇到__break__, __continue__,__return__语句, 则`finally`子句在执行`break,`,`continue`, `return`语句之前被执行.
- 如果`finally`子句中包含一个`return`语句, 则`finally`子句的`return`语句将在执行`try`子句的`return`语句之前取代后者的执行。

> NOTE: finally子句在任何情况下都会被执行. 

## 预定义的清理操作

某些对象定义了在不再需要该对象时要执行的标准清理操作, 无论使用该对象的操作时成功还是失败。

```python
for line in open("myfile.txt"):
    print(line, end=" ")
```

这个代码问题在于, 它在这部分代码执行完后, 会使文件在一段不确定的时间内处于打开状态。在简单脚本中不是问题, 但对于较大的应用程序来说可能是个问题。`with`语句允许像文件这样的对象能够以一种确保它们的到及时和正确的清理的方式使用。

```python
with open("myfile.txt") as f:
    for line in f:
        print(line, end=" ")
```

> NOTE: 执行完语句后, 即使在处理行时遇到问题, 文件f也始终会被关闭. 和文件一样，提供预定义清理操作的对象将在其文档中指出这一点。